### ISSUE TITLE
Incorrect years for some conferences

### ISSUE THREAD

**Issue by tagrikola** [cryptobib/db#111]
I noticed that for some conferences, the year field is incorrect.

For instance, CRYPTO 1991 uses year field 1992, Eurocrypt 1992 uses year field 1993, Eurocrypt 1993 uses year field 1994, CRYPTO 1993 uses year field 1994, Eurocrypt 1994 uses year field 1995.
This seems to be the case for all CRYPTOs between 1984 and 1993 and Eurocrypts between 1982 and 1994.

I have not checked if this also applies to other conferences.

**Comment by fabrice102** [comment]
See https://github.com/cryptobib/db/issues/3#issuecomment-147208271
