### ISSUE TITLE
CHES2021  one paper has wrong titles

### ISSUE THREAD

**Issue by yberlin** [cryptobib/db#118]
https://cryptobib.di.ens.fr/
In this link, I download the crypto.bib file. I search for the paper published in TCHES2021 issue2.
This paper name should be "Fault Attacks on CCA-secure Lattice KEMs" in https://tches.iacr.org/index.php/TCHES/article/view/8787
But in the file it is Fault attacks on lattice-based {KEMs}

**Comment by michelabdalla** [comment]
Fixed. Thank you for letting us know.
