### ISSUE TITLE
spurious character in EPRINT:Castelluccia06

### ISSUE THREAD

**Issue by kmccurley** [cryptobib/db#135]
I have corrected a problem in eprint that showed up in cryptobib as well. In crypto_db.bib there is an occurrence of \\" which has caused a problem with a [bibtex parser](https://github.com/SublimeText/LaTeXTools/issues/757) and also caused problems with our work on the new IACR journal. The error is in EPRINT:Castelluccia06 where it has \\". It should be just "

I have already corrected this in https://eprint.iacr.org/2006/416

**Comment by michelabdalla** [comment]
Fixed.
