### ISSUE TITLE
TCHES proceedings are listed wrong

### ISSUE THREAD

**Issue by thomwiggers** [cryptobib/db#141]
The TCHES proceedings in `crypto_conf_list.bib` are attributed to LNCS rather than TCHES

**Comment by michelabdalla** [comment]
The entries in crypto_conf_list.bib are actually not being used for TCHES. These entries were used to import CHES papers when the conference proceedings were being published by Springer.

**Comment by thomwiggers** [comment]
CHES papers haven't been published by LNCS since 2018, but there are listings for CHES 2021..2018.

**Comment by michelabdalla** [comment]
I removed those entries from crypto_conf_list.bib and abbrev.bibyml
