### ISSUE TITLE
Apostrophes in bibtex keys (identifiers) break biber

### ISSUE THREAD

**Issue by Jamtis** [cryptobib/db#144]
Hi,

the current commit of the export repo [https://github.com/cryptobib/export/commit/041e0ec43d7a9ede04e2a0dcb9203d7da10a7f2d](https://github.com/cryptobib/export/commit/041e0ec43d7a9ede04e2a0dcb9203d7da10a7f2d)(maybe previous ones as well) contains two keys `EPRINT:BeiD'AVer21` and `EPRINT:ThiO'FDew21` with apostrophes.
This breaks biber such that it doesn't recognize any keys anymore (as least for me).
I searched a bit and did not find an official statement that bibtex keys should be apostrophe-free, but I did find this [thread](https://groups.google.com/g/comp.text.tex/c/4u-v-3OxaRg) confirming that apostrophes in bibtex keys cause issues.

I took a look at the DBLP entries and their bibtex keys but they don't contain apostrophes, thus I guess that cryptobib creates the keys.

Best,
Nicholas

PS: As a hotfix, manually deleting the apostrophes resolved the issue.

**Comment by michelabdalla** [comment]
I just committed the fix.
