### ISSUE TITLE
ToSC update

### ISSUE THREAD

**Issue by Cryptosaurus** [cryptobib/db#200]
The last 6 issues of ToSC are missing in cryptodb, is it possible to include them?

I can try to submit a pull request, but I'm not sure how you're handling ToSC: there is a comment in config.py saying: "Warning: we are not using the import.py script for ToSC".

**Comment by michelabdalla** [comment]
Added ToSC 2021 (Issue 4), ToSC 2022 (Issues 1-4) for now. Will add other missing ones when they show up on DBLP.

**Comment by Cryptosaurus** [comment]
Thanks!
