### ISSUE TITLE
crossrefs in non-crossref crypto.bib

### ISSUE THREAD

**Issue by maeher** [cryptobib/db#21]
My understanding is that the crypto.bib file should not contain cross references.

However, there are three books in the current crypto.bib that are cross referenced:
NguZhe10, JoyTun12, SadNac10.

**Comment by fabrice102** [comment]
Thank you for this report.
These entries are currently generated via a different process than the other entries: they are hardcoded in `crypto_misc.bib`.

We will think about a way to remove these crossrefs in `crypto.bib`.

If your main issue is that fact that the entries NguZhe10, JoyTun12, SadNac10 appear in your bibliography while you only cite entries that crossref them, you can use BibTeX with the option `--min-crossrefs=1000` as a workaround.

**Comment by maeher** [comment]
Thanks for the answer, but actual problem is different: When trying to cite MaeVer10, bitex throws the error

A bad cross reference---entry "MaeVer10"
refers to entry "SadNac10", which doesn't exist

Obviously this is not true, SadNac10 **does** exist. I have now been able to figure out what the problem is. According to the bibtex documentation from 1988:

> To guarantee that this scheme works, however, a cross-referenced entry
must occur later in the database files than every entry that cross-references
it. Thus, putting all cross-referenced entries at the end makes sense.

In the crypto.bib file, however, the referenced entry precedes the referencing one, causing bibtex to throw an error. When the order is switched everything works fine.

**Comment by michelabdalla** [comment]
I changed the order of the entries in the respective files. Hopefully it works now.

**Comment by pfasante** [comment]
I guess this can also be closed by now?
