### ISSUE TITLE
Financial Cryptography and Data Security 2011 is registered as 2012

### ISSUE THREAD

**Issue by SimonErfurth** [cryptobib/db#217]
When citing papers from Financial Cryptography and Data Security 2011, they incorrectly say that they are from 2012.

To reproduce: `\cite{FC:CEVG11}`.

https://ifca.ai/fc11/index.html

**Comment by thomwiggers** [comment]
I think this is another occurrence of #170

**Comment by SimonErfurth** [comment]
Having looked up the proceedings on Springer's website, I think you are correct.
