### ISSUE TITLE
Replace "_" with "\_" in doi

### ISSUE THREAD

**Issue by xagawa** [cryptobib/db#221]
The current cryptobib with splncs04.bst causes a lot of errors because of `_` in typical doi of papers in LNCS. 
Replacing `_` with `\_` in doi eliminates this type of error and works well with and without hyperref. 

splncs04.bst will output 
```
\providecommand{\url}[1]{\texttt{#1}}
\providecommand{\urlprefix}{URL }
\providecommand{\doi}[1]{https://doi.org/#1}
```
just after \begin{thebibliography}{nn}. 
When doi contains plain `_`, say, `10.10_1`, this is converted as `https://doi.org/10.10_1` and we have the error `Missing $ inserted`.

**Comment by GeeLaw** [comment]
Adding a version that works without `hyperref`:

```tex
\documentclass{article}

% This excerpt of code is placed in the public domain.
\makeatletter
\catcode`\~=12\relax
\def\doi{\begingroup\catcode`\%=12\relax\doi@}
\def\doi@#1{\endgroup DOI {\ttfamily\doi@loop#1\doi@end}}
\def\doi@loop{\@ifnextchar\doi@end{\doi@end}{\begingroup\let\bgroup\relax
  \@ifnextchar\doi@brace@{\endgroup\doi@brace}{\endgroup\doi@token}}}
\let\doi@brace@\bgroup
\def\doi@brace#1{\string{\doi@loop#1\doi@end\string}\doi@loop}
\def\doi@token#1{\expandafter\doi@check\string#1\doi@loop}
\def\doi@check{\@ifnextchar~{\raisebox{-0.2em}}{}}
\def\doi@end\doi@end{}
\catcode`\~=13\relax
\makeatother

\begin{document}
\doi{`1234567890-=~!@#$%^&*()_+[]\ {xyz}|;':",./<>?\egroup\bgroup}.
\end{document}
```

It feels wrong to skew the simplest, unescaped encoding of DOI due to incapability of certain TeX macros.

**Comment by xagawa** [comment]
@GeeLaw
Thank you for the fixes! The first one works well and I'll use it with `\urlstyle{same}` to use roman font as llncs did.
