### ISSUE TITLE
Use url field for urls

### ISSUE THREAD

**Issue by malb** [cryptobib/db#23]
Currently crypto.bib uses the `note` field for URLs. However, the canonical field for URLs is `url` and many tools expect it there, cf. tmalsburg/helm-bibtex/pull/185 It would be great of URLs could be moved to the url field.

**Comment by pfasante** [comment]
in PR #25 @fabrice102 said that old styles do not use the url field and thus they are unsure how to cope with this in an backward compatible way.
Would it be a solution to duplicate the url and have them in note _and_ url fields?

**Comment by malb** [comment]
I have no strong opinion either way. I'd guess `url` is now meant to be the canonical way (?)

**Comment by fabrice102** [comment]
The issue with keeping both `url` and `note` is that the url appears twice in some cases.
The issue with having only `url` is that classical BibTeX styles would not work anymore: http://www.tex.ac.uk/FAQ-citeURL.html

Maybe, we should still switch to url.

**Comment by fabrice102** [comment]
We decided to use the url field.
