### ISSUE TITLE
Wrong Double Quotation Mark in File 'abbrev3.bib'

### ISSUE THREAD

**Issue by RunzhiZeng** [cryptobib/db#255]
In line 657 of the file 'abbrev3.bib', the double quotation marks which may cause a BibTeX error.

Change this line:

@string{acnsname = ""International Conference on Applied Cryptography and Network Security}

to:

@string{acnsname = "International Conference on Applied Cryptography and Network Security"}

Then it should work again.

**Comment by michelabdalla** [comment]
This issue has been addressed in the current version
