### ISSUE TITLE
Fix warnings and errors in db

### ISSUE THREAD

**Issue by pfasante** [cryptobib/db#26]
I tried to compile the whole cryptobib to see if changes broke anything:

```
\documentclass{scrartcl}

\usepackage[american]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage{csquotes}

\usepackage{biblatex}
\bibliography{abbrev3,crypto_db,crypto_conf_list}
\begin{document}
\nocite{*}
\printbibliography{}
\end{document}
```

But apparently, there are some errors, like invalid characters in labels, multiple "and" in author fields and so on. Most of them is easy to fix, I'll prepare a PR in a moment.
But one warning is:
> WARN - BibTeX subsystem: /tmp/p8quxHBGKq/crypto_db.bib_6845.utf8, line 117842, warning: undefined macro "icalp16"
(this appears for each ICALP 16 entry). The problem here is, we need either icalp16-1 or -2, I guess.
I do not see a quick way to figure out, which label is the correct one, so I'll skip this for now.
Another warning is the multiple month one, already mentioned in Issue #22 by @katrielalex.

**Comment by pfasante** [comment]
the remaining errors I get are (apart from the months ones):

> WARN - BibTeX subsystem: /tmp/p8quxHBGKq/crypto_db.bib_6845.utf8, line 117842, warning: undefined macro "icalp16"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4867, warning: undefined macro "icalp16key"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4868, warning: undefined macro "icalp16name"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4869, warning: undefined macro "icalp16name"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4870, warning: undefined macro "icalp16vol"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4874, warning: undefined macro "icalppub16"
> WARN - BibTeX subsystem: /tmp/OIS0o67JJB/crypto_conf_list.bib_7210.utf8, line 4875, warning: undefined macro "mylipics"

**Comment by pfasante** [comment]
Maybe these ICALP warnings are due to an old abbrev3.bib file on my side.

**Comment by katrielalex** [comment]
I don't see them (though the compile is rather slow)---just the month ones. If that helps :)

**Comment by fabrice102** [comment]
I do not see them either. I think you might indeed have an outdated `abbrev3.bib`.

**Comment by pfasante** [comment]
Yes, they were due to an old abbrev3.bib.

**Comment by fabrice102** [comment]
Thanks for fixing these issues.
Currently our testing system only uses BibTeX. I'm adding an additional test suite with Biber, as it seems to be much better to catch errors.
