### ISSUE TITLE
abbrev0, abbrev2 broken

### ISSUE THREAD

**Issue by mklss** [cryptobib/db#266]
Thanks for maintaining cryptobib, I very much depend on it and it has always worked well. Which is why it took me quite some time to figure out that the current problem appears to be within cryptobib, and not my latex documents.

A minimal example is
```
\documentclass{article}

\usepackage[backend=bibtex,style=alphabetic]{biblatex} % Biber seems to work but runs for minutes...
% \addbibresource{cryptobib/abbrev3.bib} % This works
% \addbibresource{cryptobib/abbrev2.bib} % This doesn't work
% \addbibresource{cryptobib/abbrev1.bib} % This works
\addbibresource{cryptobib/abbrev0.bib} % This doesn't work
\addbibresource{cryptobib/crypto.bib}

\title{Title}
\author{Author}
\date{Date}


\begin{document}
\maketitle{}

Error:~\cite{EC:Damgard00}

Alphabetic:~\cite{C:ChaTesZhu24}.

\printbibliography{}

\end{document}
```

On my system (BibTeX, Version 0.99d (TeX Live 2025/dev/Debian)), using abbrev0 and abbrev2 is broken. But I didn't test abbrev1 too much.
Bibtex complains about 
```
Too many commas in name 1 of "Springer, Berlin, Heidelberg, Germany" for entry EC:Damgard00
while executing---line 2816 of file biblatex.bst
```

I suspect the offending string is `@string{springer_berlin_heidelberg = "Springer, Berlin, Heidelberg, Germany"}` but don't know how to fix it.

(Bonus candidate bug: I expected C:ChaTesZhu24 to abbreviate to CTZ24 but it yields CATZ24, due to a hyphenated Last-Name which isn't written as Last{-}Name or however this is correctly encoded for Bibtex.)

**Comment by fabrice102** [comment]
Thanks for your feedback!

We're working on a temporary workaround:
https://github.com/cryptobib/db/pull/267
