### ISSUE TITLE
Wrong year in early nineties CRYPTO conferences

### ISSUE THREAD

**Issue by RobTrifiletti** [cryptobib/db#3]
Hi!

I just cited Pedersen's crypto paper from 91 and in the references it shows up as this occurred in 1992. I did a little digging and the problem is that in the @Proceedings for C91 the year is off by 1. Looking at the proceedings for 90, 92, 93, 89, 88, 87, etc the year attribute is also wrong here. This makes me think it might be a general problem and maybe extend to other conferences as well. Starting from CRYPTO94 and up everything seems fine and as well for CRYPTO84 and down.

**Comment by RobTrifiletti** [comment]
Update, I just went through Eurocrypt and here there are also errors. For instance for the proceedings EC89 the year is listed 1990.

This is by the way in the cross_reference version of your database, the file crypto_crossref.bib

**Comment by michelabdalla** [comment]
Dear Rob,

Please accept my apologies for this late reply.

In fact, the dates are correct in the database as they refer to the year in which the proceedings were published. While the proceedings of Crypto and Eurocrypt are now available by the time these conferences take place, this was not the case in the past. 

Regards,
Michel

**Comment by RobTrifiletti** [comment]
Dear Michel,
No worries, thank you for replying :)
Now I feel silly for posting this as an issue. However I'm still unsure what is the correct way to cite these papers then, since for instance in the above example of Pedersen's paper I've seen countless citations as Ped91, while actually according to the proceedings date it then should be Ped92. As one of the authors of this bibliography database what is your take on this? I'm sorry for perhaps a very novice question.

Best

**Comment by pfasante** [comment]
While this question was asked quite some time ago, I would say Ped92 is the correct way, but actually this is only a label to the full citation in the bibliography and thus should not matter that much.

I suppose to close this issue.
