### ISSUE TITLE
DOI's missing for FSE conferences pre-2013

### ISSUE THREAD

**Issue by pfasante** [cryptobib/db#32]
The FSE papers only have a DOI from 2013 on.
Do you have some (semi-) automatic way to fetch these from the springer homepage or something?

**Comment by fabrice102** [comment]
Unfortunately, we currently don't have an automatic tool to do that. We actually wanted to add DOI on all the old conferences, for a long time now. But we are not sure when we will have time to do it.

If you want to develop a tool for that task, feel free to do it and send pull request in https://github.com/cryptobib/db_import. We would be very grateful.

**Comment by pfasante** [comment]
Ok, I guess I will also not really have some spare time for this :/ But I'll try to keep it in mind.
