### ISSUE TITLE
Incorrect Name for AsiaCCS

### ISSUE THREAD

**Issue by maeher** [cryptobib/db#4]
Hi,

I just spotted that the names of all AsiaCCS conferences in the database are incorrect. They mistakenly reference the name of CCS instead.
I.e., in all abbrev files, the names of the AsiaCCS conferences is set as in the following example
> @string{asiaccs11name =         "ASIACCS 11: 6th " # ccsname}

Where "ccsname" should actually be "asiaccsname".

**Comment by fabrice102** [comment]
Thank you for letting us know about this problem. It has been fixed.
