### ISSUE TITLE
Same paper exists twice.

### ISSUE THREAD

**Issue by maeher** [cryptobib/db#52]
The database seems to contain at least one paper twice, once as "Cocks01" and once as IMA:Cocks01, as listed below.

```
@InProceedings{Cocks01,
  author =       "Clifford Cocks",
  title =        "An Identity Based Encryption Scheme Based on Quadratic Residues",
  pages =        "360--363",
  booktitle =    "Cryptography and Coding, 8th IMA International Conference",
  editor =       "Bahram Honary",
  publisher =    springer,
  address =      "Cirencester, UK",
  series =       mylncs,
  volume =       2260,
  month =        dec # "~17--19,",
  year =         2001,
}
```

```
@InProceedings{IMA:Cocks01,
  author =       "Clifford Cocks",
  title =        "An Identity Based Encryption Scheme Based on Quadratic Residues",
  pages =        "360--363",
  editor =       ima01ed,
  booktitle =    ima01name,
  volume =       ima01vol,
  address =      ima01addr,
  month =        ima01month,
  publisher =    imapub,
  series =       mylncs,
  year =         2001,
}
```
I'm not sure if this was done on purpose. (I'm also not sure if it should be changed given that it would break backwards compatibilty.) But when choosing the wrong one, i.e. "Cocks01", the entry is also not affected by the abbrev files.

**Comment by fabrice102** [comment]
Thanks for the comment.

I think we added the IMA conference a long time after adding Cocks01, hence the collision.
For backward compatibility, we will keep Cocks01 and update it such that it is consistent with IMA:Cocks01.
